In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
print(a)

[1 2 3 4 5 6 7 8 9]


In [4]:
rabbi = a.reshape((3,3))
print(rabbi)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

In [ ]:
r = b.reshape((20,1))
r

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20]])

In [ ]:
r = b.reshape((2,10))
r

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [ ]:
r = b.reshape((10,2))
r

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [ ]:
r = b.reshape((4,5))
r

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [ ]:
r = b.reshape((5,4))
r

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [ ]:
r*10

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120],
       [130, 140, 150, 160],
       [170, 180, 190, 200]])

In [ ]:
r+10

array([[11, 12, 13, 14],
       [15, 16, 17, 18],
       [19, 20, 21, 22],
       [23, 24, 25, 26],
       [27, 28, 29, 30]])

In [ ]:
r-10

array([[-9, -8, -7, -6],
       [-5, -4, -3, -2],
       [-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [ ]:
r/10

array([[0.1, 0.2, 0.3, 0.4],
       [0.5, 0.6, 0.7, 0.8],
       [0.9, 1. , 1.1, 1.2],
       [1.3, 1.4, 1.5, 1.6],
       [1.7, 1.8, 1.9, 2. ]])

In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [ ]:
arr= np.array([1,2,3,4,5,6,7,8,9])
print(arr[2])

3


In [ ]:
print(arr[2] + arr[6])

10


2D array

In [ ]:
arr= np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,1])

7


3D

In [ ]:
arr= np.array([[[1,2,3], [4,5,6]],[[7,8,9],[10,11,12]]])
print(arr[1,1,1])

11


In [ ]:
arr= np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1, -1])

10


slicing

In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:-4])

[2 3]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[4:])

[5 6 7]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[:4])

[1 2 3 4]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
print(arr[::2])

[1 3 5 7]


spliting

In [ ]:
arr= np.array([1,2,3,4,5,6,7,8,9])
sumu = np.array_split(arr,4)
sumu

[array([1, 2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [ ]:
print(sumu[2])

[6 7]


In [ ]:
arr= np.array([1,2,3,4,5,6,7])
sumu = np.array_split(arr,5)
print(sumu[0])
print(sumu[1])
print(sumu[2])

[1 2]
[3 4]
[5]


In [ ]:
arr= np.array([[1,2,3], [4,5,6],[7,8,9],[10,11,12], [13,14,15],[16,17,18]])
sumu = np.array_split(arr,3)
print(sumu)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


array Shape

In [ ]:
a = np.array([1,2,3])
a.dtype


dtype('int64')

In [ ]:
b = np.array([1.5,2,3,4,5,6,7,8,9])
b.dtype

dtype('float64')

In [ ]:
b = np.array(['Rabbi','Sumu'])
b.dtype

dtype('<U5')

In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2)) #stack array horigontally
print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
from numpy.core.multiarray import concatenate
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


# Numpy array slicing

In [ ]:
       # Define the original matrix
matrix = np.array([[0, 1, 2, 3, 4],
                  [5, 6, 7, 8, 9],
                  [10, 11, 12, 13, 14]])

# Use slicing to extract the submatrix
submatrix = matrix[:2,2:4]


print(submatrix)


[[2 3]
 [7 8]]


In [ ]:

sumu = np.array([[0,1,2,3,4],
                 [5,6,7,8,9],
                  [10,11,12,13,14]])
prantee = sumu[:,::2]
print(prantee)

[[ 0  2  4]
 [ 5  7  9]
 [10 12 14]]


In [ ]:
sumu = np.array([[0,1,2,3,4],
                 [5,6,7,8,9],
                  [10,11,12,13,14]])
prantee = sumu[::2,::3]
print(prantee)

[[ 0  3]
 [10 13]]


search

In [ ]:
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr==4)
print(x)

(array([3, 5, 6]),)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr %2 == 0)
print(x)

(array([1, 3, 5, 7]),)


In [ ]:
arr = np.array([1,2,3,4,5,6,7,8])
x = np.where(arr%2 == 1)
print(x)

(array([0, 2, 4, 6]),)


In [ ]:
a = np.arange(30).reshape((5,6))
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
arr = np.arange(20).reshape((4,5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
i = np.array([[1,2], [0,2]])
j = np.array([[1,0], [1,3]])
arr[i,j]


array([[ 6, 10],
       [ 1, 13]])

In [ ]:
a = np.arange(15).reshape((3,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
b = (a%3 == 0)
b

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

In [ ]:
a[b]

array([ 0,  3,  6,  9, 12])

In [ ]:
b= (a%3 != 0)
b

array([[False,  True,  True, False,  True],
       [ True, False,  True,  True, False],
       [ True,  True, False,  True,  True]])

In [ ]:
a[b]

array([ 1,  2,  4,  5,  7,  8, 10, 11, 13, 14])

np sorting array

In [ ]:
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array([3,2,0,1])
print(np.sort((arr)) [::-1])

[3 2 1 0]


In [ ]:
arr = np.array(['orange','lemon','mango'])
print(np.sort(arr))

['lemon' 'mango' 'orange']


In [ ]:
arr = np.array([41,42,43,44])
x=[True,False,True,False]
newarr= arr[x]
print(newarr)

[41 43]


In [ ]:

arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]

# Find values in arr where x is False
false_values = arr[np.logical_not(x)]

print(false_values)


[42 44]


In [ ]:
arr =np.array([41,42,43,44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)


[False False  True  True]
[43 44]


In [ ]:
#random value
arr =np.array([1,2,3,4])
print(np.random.randint(arr))


[0 1 0 3]


In [ ]:
np.random.randint(5, size=(2, 4))


array([[4, 3, 0, 4],
       [3, 2, 2, 3]])

In [ ]:
#Zeroes
arr =np.zeros(5)
print(arr)

[0. 0. 0. 0. 0.]


In [ ]:

#sorted index


# Original array
array = np.array([10, 52, 62, 16, 16, 54, 453])
print(array)

# Indices of the sorted elements of a
# given array
indices = np.argsort(array)
print(indices)

[ 10  52  62  16  16  54 453]
[0 3 4 1 5 2 6]


In [ ]:
arr =np.array([9,2,8,4,5,12,7,6])
b = np.argsort(arr)
print(b) #not Need

[1 3 4 7 6 2 0 5]


In [ ]:
#Max values
arr = np.array([[1,2,3],[3,4,5],[7,8,9]])
b = np.max(arr)
print(b)

9


In [ ]:
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second and fourth elements of the second and fourth rows ")
print(arra_data[1:3,1:3])
#sumu = np.array([[0,1,2,3,4],
               #  [5,6,7,8,9],
                 # [10,11,12,13,14]])
#prantee = sumu[::2,::3]
#print(prantee)

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second and fourth elements of the second and fourth rows 
[[ 5  6]
 [ 9 10]]
