Problem 01: ***Reverse Array***

In [ ]:
import numpy as np

In [ ]:
def reverse_array(array):
   return array[::-1]

In [ ]:
input_string = input()
array = np.array(input_string.split(), dtype=float)
reversed_array = reverse_array(array)
print(reversed_array)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]




```
# This is formatted as code
```

**`Problem 02`**
Shape Reshape


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
np= arr.reshape((3, 3))
print(np)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


**Problem 03**
Tranpose and Flatten


In [ ]:
n, m = map(int, input().split())


matrix = [list(map(int, input().split())) for _ in range(n)]

np_array = np.array(matrix)

transpose_array = np.transpose(np_array)

flatten_array = transpose_array.flatten()

print(transpose_array)
print(flatten_array)


2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 3 2 4]


Problem 04
#Concate

In [ ]:
 n, m, p = map(int, input().split())
array1 = [list(map(int, input().split())) for _ in range(n)]

array2 = [list(map(int, input().split())) for _ in range(m)]
np_array1 = np.array(array1)
np_array2 = np.array(array2)
concatenated_array = np.concatenate((np_array1, np_array2), axis=0)

print(concatenated_array)



4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


Problem 05
#Zeros and Ones

In [ ]:
shape = tuple(map(int, input().split()))

zeros_array = np.zeros(shape, dtype=int)
ones_array = np.ones(shape, dtype=int)

print(zeros_array)
print(ones_array)


3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


#6. Eye And Identity

In [ ]:
import numpy as np
np.set_printoptions(sign=' ')

n, m = map(int, input().split())
result_array = np.eye(n, m)

print(result_array)


3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


#7: Array Math


In [ ]:
n, m = map(int, input().split())
array1 = np.array([list(map(int, input().split())) for _ in range(n)])
array2 = np.array([list(map(int, input().split())) for _ in range(n)])

sum_result = np.add(array1, array2)
diff_result = np.subtract(array1, array2)
prod_result = np.multiply(array1, array2)
div_result = np.floor_divide(array1, array2)
mod_result = np.mod(array1, array2)
power_result = np.power(array1, array2)

print(sum_result)
print(diff_result)
print(prod_result)
print(div_result)
print(mod_result)
print(power_result)


1 4
 1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


#8: Floor, cell and rent

In [ ]:
import numpy as np
np.set_printoptions(sign=' ')
elements = np.array(input().split(), dtype=float)

print(np.floor(elements))
print(np.ceil(elements))
print(np.rint(elements))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


#9: Sum n Prod

In [ ]:
n, m = map(int, input().split())

arr = np.array([list(map(int, input().split())) for _ in range(n)])
sum_along_axis_0 = np.sum(arr, axis=0)

product_of_sum = np.prod(sum_along_axis_0)

print(product_of_sum)


2 2
1 2
3 4
24


#prob_10 Min Max

In [ ]:
n, m = map(int, input().split())
arr = np.array([list(map(int, input().split())) for _ in range(n)])
min_along_axis_1 = np.min(arr, axis=1)
max_of_minimums = np.max(min_along_axis_1)

print(max_of_minimums)


 4 2
2 5
3 7
1 3
4 0
3


#Prob_11: Mean, Var, std

In [ ]:


n, m = map(int, input().split())
arr = np.array([list(map(int, input().split())) for _ in range(n)])

mean_along_axis_1 = np.mean(arr, axis=1)
variance_along_axis_1 = np.var(arr, axis=1)
std_deviation_along_axis_1 = np.std(arr, axis=1)

print(mean_along_axis_1)
print(variance_along_axis_1)
print(std_deviation_along_axis_1)


2 2
1 2
3 4
[ 1.5  3.5]
[ 0.25  0.25]
[ 0.5  0.5]


#Prob_12: Dot and Cross

In [ ]:

n = int(input())


matrix1 = np.array([list(map(int, input().split())) for _ in range(n)])
matrix2 = np.array([list(map(int, input().split())) for _ in range(n)])
result_matrix = np.dot(matrix1, matrix2)

print(result_matrix)


2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


#Prob_13: Inner/Outer

In [ ]:

array1 = np.array(list(map(int, input().split())))
array2 = np.array(list(map(int, input().split())))

inner_product = np.inner(array1, array2)
outer_product = np.outer(array1, array2)

print(inner_product)
print(outer_product)

0 1
2 3
3
[[0 0]
 [2 3]]


#Prob_14: Polynomials

In [ ]:

coefficients = list(map(float, input().split()))
x = float(input())
result = np.polyval(coefficients, x)


print(result)


1. 1 2 3
0
3.0


#Prob_15: Linear Algebra

In [ ]:

n = int(input())
matrix = []
for _ in range(n):
    row = list(map(float, input().split()))
    matrix.append(row)
matrix = np.array(matrix)
determinant = round(np.linalg.det(matrix), 2)

print(determinant)


2
 1.1 1.1
1.1 1.1
0.0
